spring:
  application:
    name: product-service

  config:
    import: optional:configserver:http://config-server:8888

  cloud:
    config:
      fail-fast: false

  data:
    mongodb:
      uri: mongodb://mongo1:27017/productdb

# ✅ Actuator
management:
  endpoints:
    web:
      exposure:
        include: refresh,health,info

# ✅ Eureka
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://discovery-server:8761/eureka #defaultZone: http://admin:admin@discovery-server:8761/eureka

  instance:
    prefer-ip-address: true